<?php

/**
 * PluginMerchantAccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMerchantAccountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMerchantAccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMerchantAccount');
    }
    
    /**
     * Efficiently return the primary key of the merchant account with this config key.
     *
     * @param string $key 
     * @return int ID
     */
    public function selectIdFromKey($key)
    {
      $q = Doctrine_Query::create()
          ->select('m.id')
          ->from('MerchantAccount m')
          ->addWhere('m.config_key = ?');
      $results = $q->execute(array($key), Doctrine_Core::HYDRATE_NONE);
      
      return isset($results[0][0]) ? $results[0][0] : null;
    }
}