<?php

/**
 * PluginMerchantAccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMerchantAccountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMerchantAccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMerchantAccount');
    }
}