<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginPurchase extends BasePurchase
{
  public function generatePurchaseNumber()
  {
    $maxNumber = Doctrine::getTable('Purchase')->getMaxPurchaseNumber();
    if (!$maxNumber) {
      $maxNumber = date('Y').str_pad(330, 7, "0", STR_PAD_LEFT);
    }
    
    return $maxNumber + 1;
  }
}