<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPurchaseTable extends Doctrine_Table
{
  public function getMaxPurchaseNumber()
  {
    $q = Doctrine_Query::create()
      ->select('MAX(p.purchase_number) as max_purchase_number')
      ->from('Purchase p');

    $result = $q->execute(array(), Doctrine::HYDRATE_ARRAY);
    
    return isset($result[0]['max_purchase_number']) ? ($result[0]['max_purchase_number']) : 0;
  }
  
  public function generatePurchaseNumber()
  {
    $maxNumber = $this->getMaxPurchaseNumber();
    if (!$maxNumber) {
      $maxNumber = date('Y').str_pad(330, 7, "0", STR_PAD_LEFT);
    }
    
    return $maxNumber + 1;
  }
  
}