<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPromoCodeTable extends Doctrine_Table
{
  /**
   * Validator is placed in here in the table class because it is used 
   * in a few different forms: CheckoutPageOneForm, PromoCodeCheckoutForm, RegistrationForm
   *
   * @param string $validator 
   * @param string $code 
   * @return $code
   * @throws sfValidatorError
   */
  public static function validateCode($validator, $code) 
  {
    if (($promoCode = self::findValidByCode($code)) && $promoCode->exists())
    {
      return $code;
    } 
    else 
    {
      throw new sfValidatorError($validator, 'invalid', array('value' => $code));
    }
  }
  
  /**
   *  SELECT * FROM promo_code 
   *  WHERE `code` = 'free'
   *  AND (num_uses IS NULL OR (use_count < num_uses))
   *  AND (valid_from IS NULL OR valid_from <= NOW())
   *  AND (valid_to IS NULL OR valid_to >= NOW())
   *
   * @param string $code 
   * @return void
   * @author Scott Meves
   */
  public static function findValidByCode($code)
  {
    $now = date('Y-m-d H:i:s');
    
    return Doctrine_Query::create()
      ->from('PromoCode p')
      ->where('p.code = ?', $code)
      ->andWhere('p.num_uses IS NULL OR (p.use_count < p.num_uses)')
      ->andWhere('p.valid_from IS NULL OR p.valid_from <= ?', array($now))
      ->andWhere('p.valid_to IS NULL OR p.valid_to >= ?', array($now))
      ->fetchOne();
  }
  
  public static function createCode($length = 10) 
  { 
    $chars = "ABCDEFGHIJKLMNPQRSTUVWXYZ123456789"; 
    $count = 34;
    $i = 0; 
    $pass = ''; 

    while ($i <= $length) { 
        $num = rand(0,34);
        $tmp = substr($chars, $num, 1); 
        $pass .= $tmp;  // ((($i==0) || $i%4) ? '' : '-') . 
        $i++; 
    } 

    return $pass;
  }
}