<?php

/**
 * PluginPromoCodeProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPromoCodeProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPromoCodeProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPromoCodeProduct');
    }
}