<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPromoCodeTable extends Doctrine_Table
{
  public static function validateCode($validator, $code) 
  {
    if (($promoCode = self::findValidByCode($code)) && $promoCode->exists())
    {
      return $code;
    } 
    else 
    {
      throw new sfValidatorError($validator, 'invalid', array('value' => $code));
    }
  }
  
  /**
   *  SELECT * FROM promo_code 
   *  WHERE `code` = 'free'
   *  AND (num_uses IS NULL OR (use_count < num_uses))
   *  AND (valid_from IS NULL OR valid_from <= NOW())
   *  AND (valid_to IS NULL OR valid_to >= NOW())
   *
   * @param string $code 
   * @return void
   * @author Scott Meves
   */
  public static function findValidByCode($code)
  {
    $now = date('Y-m-d H:i:s');
    
    return Doctrine_Query::create()
      ->from('PromoCode p')
      ->where('p.code = ?', $code)
      ->andWhere('p.num_uses IS NULL OR (p.use_count < p.num_uses)')
      ->andWhere('p.valid_from IS NULL OR p.valid_from <= ?', array($now))
      ->andWhere('p.valid_to IS NULL OR p.valid_to >= ?', array($now))
      ->fetchOne();
  }
}