<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginPurchaseProduct extends BasePurchaseProduct
{
  public function __toString()
  {
    return $this['Product']->__toString();
  }
}