<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginPromoCode extends BasePromoCode
{
  public function incrementUseCount(Doctrine_Connection $conn = null)
  {
    if (!$this->use_count) {
      $this->use_count = 0;
    }
    
    $this->use_count += 1;
    
    return $this->save($conn);
  }
  
  public function getProductIds()
  {
    $ids = array();
    
    $results = Doctrine_Query::create()
      ->select('p.product_id')
      ->from('PromoCodeProduct p')
      ->where('p.promo_code_id = ?', $this->getId())
      ->setHydrationMode(Doctrine::HYDRATE_NONE)
      ->execute();
      
    foreach ($results as $r) {
      $ids[$r[0]] = $r[0];
    }
    
    return $ids;
  }
}
