<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginPurchase extends BasePurchase
{
  public function __toString()
  {
    
    $str = '';
    if ($date = $this->getCreatedAt()) {
      $str .= date('m/d/Y', strtotime($date));
    }
    
    $str .= ' / '.$this->getProductNames();
    /*
    if ($total = $this->getProductTotal()) {
      $str .= ' / $'.$total;
    }
    */
    return $str;
  }
  
  public function createPurchaseProduct($productId, $quantity = 1)
  {
    $pp = new PurchaseProduct();
    
    $pp['product_id'] = $productId;
    $pp['quantity'] = $quantity;
    $pp['purchase_id'] = $this['id'];
    
    return $pp;
  }
  
  public function getProductNames() 
  {
    $names = array();
    
    $results = Doctrine::getTable('Product')->
      createQuery('product')->
      select('product.id, product.name')->
      innerJoin('product.PurchaseProducts pp')->
      where('pp.purchase_id = ?', $this['id'])->
      fetchArray();
    
    foreach ($results as $result) {
      $names[] = $result['name'];
    }
    
    return implode(', ', $names);
  }
  
  /**
   * Admin generator tries to load the wrong column, bill_street2
   *
   * @return void
   */
  public function getBillStreet2()
  {
    return parent::_get('bill_street_2');
  }
    
    
  /**
   * Return the common 'term' (yearly or monthly) for all products in this purchase
   * returns false if not all purchase_products have the same term
   */
  public function getTerm()
  {
    $term = null;
    
    foreach ($this['PurchaseProducts'] as $purchaseProduct) {
      if ($term === null) {
        $term = $purchaseProduct['term'];
      } elseif ($term != $purchaseProduct['term']) {
        return false;
      }
    }
    
    return $term;
  }
    
  public function isYearly()
  {
    return $this->getTerm() == 'yearly';
  }
  
  public function isMonthly()
  {
    return $this->getTerm() == 'monthly';
  }
  
  public function preInsert($event)
  {
    $record = $event->getInvoker();

    if ( ! $record->purchase_number) {
        $record->purchase_number = Doctrine::getTable('Purchase')->generatePurchaseNumber();
    }
  }
  
  /**
   * Used to generate an invoice number
   *
   * @param string $conn 
   * @return Purchase
   */
  public static function createTemporaryPurchase($conn = null)
  {
    $purchase = new Purchase();
    $purchase->save($conn);
    
    return $purchase;
  }
}