<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPurchaseTable extends Doctrine_Table
{
  public function getMaxPurchaseNumber()
  {
    $q = Doctrine_Query::create()
      ->select('MAX(p.purchase_number) as max_purchase_number')
      ->from('Purchase p');

    $result = $q->execute(array(), Doctrine::HYDRATE_ARRAY);
    
    return isset($result[0]['max_purchase_number']) ? ($result[0]['max_purchase_number']) : 0;
  }
}